# 09 异常处理
VMIOT 支持完备异常处理机制，方便进行错误的处理与资源的可靠回收。

报告异常的几种方式：
0.  关闭
1. 一发现就报告，位置准备 （默认策略）
2. 只在任务结束时报告
3. 方式(1) + 方式(2)

在VMIOT中，可以用以下代码指定报告异常的方式：
```
#def vmiot_set_exceptionmode(emode):

#vmiot_set_exceptionmode(0)
#vmiot_set_exceptionmode(1)
#vmiot_set_exceptionmode(3)
```

### 异常的错误处理范式
```
#(1)掌握异常的错误处理范式
def TestTryNoException():
	try:
		print "No Err Here"
	except:
		print "Exception Occur"
	else:
		print "No Exception"
	finally:
		print "Finally"
	print "End"
TestTryNoException()
```
结果：
```
PRINT: No Err Here
PRINT: No Exception
PRINT: Finally
PRINT: End
```
### 常见异常处理
1. 采用捕获except RaiseExceptio方法来处理raise的异常
2. 采用捕获except AssertionError方法来处理assert的异常
3. 采用捕获except Exception: 或者 except: 的模式来捕获所有异常
4. kill一个任务的时候，该任务无法捕获这个异常，这是一个例外，但是即使这样，异常的finally也是会被执行
5. exit(-1)函数就是通过产生一个异常结束本任务的，这个异常无法被捕捉到，但是可以利用finally来完成任务的结束处理
```
print "TestRaiseExceptionCapture-----------"
def TestRaiseExceptionCapture():
	try:
		#raise "some errinfo"
		#assert False
		xxx = ttt
		raise 100
		#exit(1)
	except RaiseException,e:
		print "Raise Exception: ",e
	except AssertionError,e:
		print "AssertionError: ",e
	except Exception,e:
		print "Exception: ",e
	except:
		print "Exception Occur"
	else:
		print "No Exception"
	finally:
		print "Finally Now"
	print "Task End"
TestRaiseExceptionCapture()
```
结果：
```
PRINT: TestRaiseExceptionCapture-----------
PRINT:
==========Traceback by VMIOT (0):===========
PRINT: Exception NameError : ttt
PRINT:   (0) "main.py", line 42, in TestRaiseExceptionCapture
PRINT:   (1) "main.py", line 58, in main
PRINT:
PRINT: Exception:  234
PRINT: Finally Now
PRINT: Task End
```
### 自定义异常类
用户可以定义自己的异常类。 

**注：一定要定义一个类级别的错误code编号，从2000开始**
```
class AppException1(Exception):
	code = 2000

class SomeException(Exception):
	code = 2001
	def __init__(self,info):
		self.info = info
	def dump(self):
		print "SomeException Code: %s Info: %s" % (self.code,self.info)

def TestExceptionClass():
	try:
		raise SomeException("Bad Parameters")
		raise AppException1
	except AppException1,e:
		print "AppException1: ",e.code
	except SomeException,e:
		e.dump()
	except:
		print "Unknown Exception"
	else:
		print "no exception"
	finally:
		print "in Finally"
	print "Task End"

TestExceptionClass()
```
结果：
```
PRINT: SomeException Code: 2001 Info: Bad Parameters
PRINT: in Finally
PRINT: Task End
```